### ISSUE TITLE
UDP runtime error

### ISSUE THREAD

**Issue by Pfalra** [Pfalra/FFFilamentrecycling#1]
The udp stack prints an error while listening to the assigned port.
Maybe stack size for the corresponding task is insufficient.

**Comment by g3gg0** [comment]
got comparable issues while using ArduinoOTA in some other project.
Stack trace showed the new() call within some UDP receive code was failing.

not sure what causes that.

**Comment by Pfalra** [comment]
Up until now we used the Wemos Lolin32. Somehow this error does not occur when the code is running on the ESP32-Wroom DevKit. I just switched the board and additionally to being functional now, we have more pins we can use.
