### ISSUE TITLE
Device falls into reboot loop if I2C communication fails

### ISSUE THREAD

**Issue by Pfalra** [Pfalra/FFFilamentrecycling#3]
To recreate the scenario simply the external modules should be powered down. Seems like two tasks want to access the I2C for OLED and ADC and then the device restarts over and over again.

**Comment by Pfalra** [comment]
![Screenshot 2022-02-26 190439](https://user-images.githubusercontent.com/36314809/155854213-a7bd8477-5766-4e92-9446-95b83354143f.png)


That message makes it kinda obvious. However it's something we should take care of.

**Comment by g3gg0** [comment]
so having ADC and LCD handled in the same task should work, right?

**Comment by Pfalra** [comment]
Yep that should work, However, reading the message in the screenshot above indicates that it can be fixed by calling the yield function while init tries to get the OLED set up should also work out.

**Comment by Pfalra** [comment]
Just encountered the following:

![Screenshot 2022-02-27 143555](https://user-images.githubusercontent.com/36314809/155885976-a26b8bf7-b2f8-4068-9dd8-cddfef98f003.png)

Either we handle both I²C devices within the same task or we use semaphores to protect the interface. Otherwise this error will happen sporadically. I tend to use the latter suggestion to keep ADC and OLED handling separate.
