### ISSUE TITLE
Implementation of FPGA reading

### ISSUE THREAD

**Issue by Pfalra** [Pfalra/FFFilamentrecycling#8]
Simply the reading of the measurement values has to be implemented via Serial2. The result has to be packed into an FFF_Measurement and thrown over to the DiaAnalyzer.

**Comment by tobiornottobinoack** [comment]
Serial2 is now in place, use at PID needs further attention

**Comment by Pfalra** [comment]
That's something I'll take a look into. Just recognized that we already have a task defined just for the FPGA data reading. Dependent on the runtime of the analysis we can keep it within the PID task to ensure data consistency.
